language: csharp
solution: KonSchool.sln
mono: none

notifications:
  email:
    - maacpiash@outlook.com

branches:
  only:
    - master

matrix:
  include:
    - os: linux 
      dist: trusty # Ubuntu 14.04
      dotnet: 2.1
    - os: osx
      dotnet: 2.1.200
      # osx_image: xcode9.4 # dotnet requires at least this version

before_install:
  - if [ $TRAVIS_OS_NAME = ubuntu ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi

script:
  - dotnet restore
  - dotnet build
  # - dotnet test
