branches:
  only:
  - master
language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - dotnet test tests/KonSchool.Tests.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
